apiVersion: v1
kind: Template
labels:
  template: release-management-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template.  
metadata:
  annotations:
    openshift.io/display-name: Release Management Template
    description: |-
      This template defines a release for application, processing a template will  
      1. create a Rollout pipeline for Dev environment of specified application and version. 
         Refer BuildConfig having name ${APP_NAME}-${RELEASE_NAME}-dev-rollout
      2. TODOs : update description as more features are added into this template.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: release-management-template
parameters:
- description: The name of the application to which this template belongs. It should not have any whitespaces. for e.g. marketdata, accounts, etc.
  displayName: Application Name
  name: APP_NAME
  required: true
- description: The release name of the application. for e.g. v1, v2, apple, banana, cherry , etc
  displayName: Release Name
  name: RELEASE_NAME
  required: true
- description: Git repository url of where Jenkin files of Release pipelines are maintained. 
  displayName: Git repository URL of Jenkins Pipelines
  name: JENKINS_PIPELINE_GIT_URL
  required: true
- description: Path of jenkinsfile for Rollout pipeline. It should be relative to context directory of Git repository url of of Jenkins Pipelines. 
  displayName: Path of Rollout pipeline jenkinsfile
  name: DEV_ROLLOUT_JENKINSFILE_PATH
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}-${RELEASE_NAME}-dev
      name: ${APP_NAME}-${RELEASE_NAME}-dev-rollout
    name: ${APP_NAME}-${RELEASE_NAME}-dev-rollout
  spec:
    source:
      git:
        uri: ${JENKINS_PIPELINE_GIT_URL}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${DEV_ROLLOUT_JENKINSFILE_PATH}
        env:
          name: GIT_REPO
          value: ${JENKINS_PIPELINE_GIT_URL}
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic